module.exports.homeController = require('./HomeController')
module.exports.pagesController = require('./PagesController')
module.exports.attachmentsController = require('./AttachmentsController')
module.exports.modalAttachmentsController = require('./ModalAttachmentsController')
module.exports.settingsController = require('./SettingsController')
